# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tastypie.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField()),
                ('nick_name', models.CharField(max_length=10)),
                ('about_me', models.CharField(max_length=300)),
                ('display_image', models.ImageField(default='images/4cb7d22a-d175-49cf-a3cb-d08a03cdf7cf', upload_to=b'', verbose_name='images/')),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='main.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(default='images/03974d21-b7b9-4e99-ab2a-43039f334816', upload_to='images/')),
                ('pub_date', models.DateTimeField(default=tastypie.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserImages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(max_length=140)),
                ('pub_date', models.DateTimeField(default=tastypie.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserStatus', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField(blank=True, default=None, null=True)),
                ('image', models.FileField(default='videos/485a584a-f7c0-4e03-ada9-e59a3d949cfd', upload_to='videos/')),
                ('pub_date', models.DateTimeField(default=tastypie.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserVideo', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
    ]
