# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_image',
            field=models.ImageField(default='images/3a795b60-d956-48ef-b0c2-28c1d6bf63bc', upload_to=b'', verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(default='images/3a7c413e-7e2f-4370-8abf-bcde7c91b016', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/e02c7774-67fd-49d8-a776-d5fe83fe958d', upload_to='videos/'),
        ),
    ]
