# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161103_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_image',
            field=models.ImageField(default='images/cfe8442d-f714-4315-96ec-13cd05a3c083', upload_to=b'', verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(default='images/02aacda6-5a1d-43f4-99e9-e0a2ecba3b92', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/8e2b8608-cfa5-4e6d-9fb5-bd501f4d5e53', upload_to='videos/'),
        ),
    ]
