# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161103_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_image',
            field=models.ImageField(default='images/110baa8c-22f8-49c3-a42e-00c8a7cb5101', upload_to=b'', verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(default='images/37f4ed3e-76b7-4b4c-b699-56ea9332bd0e', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/3535d7f5-4f5c-416e-9e31-3473b35bc7f1', upload_to='videos/'),
        ),
    ]
