# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161103_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_image',
            field=models.ImageField(default='anonymous.jpg', upload_to=b'', verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(default='images/7e17a390-0d58-4332-9e46-b14a541d745b', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/2d40f341-d41e-4bcf-9128-09f51a437f3e', upload_to='videos/'),
        ),
    ]
