# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161105_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(default='images/5d7e4489-5e70-4e04-89e3-90a452dee674', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/1364c18a-8b32-4882-a3fa-2260128bd2ee', upload_to='videos/'),
        ),
    ]
