# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161105_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='highlighted',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='likkes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Video_Likes', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(default='images/5a11439b-efc4-40db-83a1-310d1109cee9', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/44a46dfd-2b26-45ec-8dca-c28cd389e654', upload_to='videos/'),
        ),
    ]
