# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161105_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/42b3ab77-8f7b-4956-a066-e4172d6c41f5', upload_to='videos/'),
        ),
    ]
