# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 14:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20161105_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='likes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='uservideo',
            name='likes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/03a6ddc5-6f9d-4ca8-beeb-9ce1c07657ec', upload_to='videos/'),
        ),
    ]
