# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 14:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20161105_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/92bc5299-c1c6-4bd3-a51f-d4a5ac720546', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='likes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
