# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 14:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20161105_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='likes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(default='videos/27d9c19e-f4cd-44b7-8bed-33717817dcda', upload_to='videos/'),
        ),
    ]
