# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20161105_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_image',
            field=models.ImageField(blank=True, default='null', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserImages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
