# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_userimages_userr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
            preserve_default=False,
        ),
    ]
