# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20161106_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimages',
            name='userr',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='user',
        ),
        migrations.AddField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to='main.Profile'),
            preserve_default=False,
        ),
    ]
