# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userimages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
