# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20161106_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='user',
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='main.UserImages'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to='main.Profile'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='UserVideo',
        ),
    ]
