# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20161107_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='main.UserImages'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
