# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20161107_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserImages'),
        ),
    ]
